upper  =: A | ... | Z
lower  =: a | ... | z
letter =: upper | lower

digit   =: 0 | ... | 9
decimal =: digit {digit}
integer =: decimal
float   =: decimal . decimal

reservedid =: let | in | where

symbol =: + | - | / | *

identifier =: letter {letter}